### ISSUE TITLE
README.md suggestions

### ISSUE THREAD

**Issue by QiZD90** [LaG1924/AltCraft#1]
Libraries `SDL2_net` and `SDL2_image` that aren't parts of the standard `SDL2` distribution should be specified as dependencies in the build section. And it could be a good idea to add terminal commands, which installs all dependencies in some popular Linux distros, to the README.

**Comment by LaG1924** [comment]
Fixed in 1ccf9068a9432a3272d66df951ff9a362f43bb3d

**Comment by developred** [comment]
Just some additional readme reccomendations : the installation steps are out of order. :)

**Comment by LaG1924** [comment]
> Just some additional readme reccomendations : the installation steps are out of order. :)

Tell me more.

**Comment by developred** [comment]
Sorry for lack of clarity!

Just wanted to say that installation step #3 is listed before installation step #2 in the readme!

Cool project y'all have going :)

**Comment by LaG1924** [comment]
Oh, ok. I got it. Thanks. Fixed in 682459892d3a55c541e4206859826dbb1610ebfe.
