### ISSUE TITLE
black screen with blue cubes :(

### ISSUE THREAD

**Issue by x35gaming** [LaG1924/AltCraft#34]

**Comment by LaG1924** [comment]
Have you installed Minecraft assets?

**Comment by LaG1924** [comment]
Also it would be nice to get your system specs and screenshot.

**Comment by x35gaming** [comment]
specs: amd rx550, amd ryzen3 2200g, 2 crappy power supplies, windows 10, 500gb hdd, 3x monitor eyefinity group + 2 other monitors

**Comment by x35gaming** [comment]
also i have copied it, still not working

**Comment by LaG1924** [comment]
Does precompiled version working?
