### ISSUE TITLE
Dev Build #3 ?

### ISSUE THREAD

**Issue by abasgames** [LaG1924/AltCraft#47]
Just asking when next build out

**Comment by LaG1924** [comment]
It is currently in active development, but before the next build there were some difficulties with the implementation of the gui and the support of the inventory. Right now, you can compile it yourself, or nicely ask me to build the latest dev version especially for you (but be prepared for all sorts of instabilities, even more than in dev build # 1 / # 2).

https://github.com/LaG1924/AltCraft/milestone/1
