### ISSUE TITLE
macOS support?

### ISSUE THREAD

**Issue by Eribetra** [LaG1924/AltCraft#49]
I've noticed that in the readme.md file, there are no macOS building instructions. Does this mean macOS support isn't implemented yet?

**Comment by LaG1924** [comment]
Unfortunately, I don't have a Mac. Therefore, I cannot guarantee the possibility and give instructions for compilation. But AltCraft uses macOS compatible libraries, so it is theoretically possible, but it might take some research to find a way to build.
