### ISSUE TITLE
What version is this currenly on? README could be better

### ISSUE THREAD

**Issue by GoodClover** [LaG1924/AltCraft#51]
Hey, I'm just wondering what Minecraft version AltCraft is currently on and how far it supports it?
Also is AltCraft just a client or does it contain the server aspects of MineCraft too?

Some more info on the README would be nice, currently is just instructions on how to compile it.

**Comment by GoodClover** [comment]
Just saw https://github.com/LaG1924/AltCraft/issues/35 docs would be nice

**Comment by uis246** [comment]
1.12.2
