### ISSUE TITLE
My ISSUE list 

### ISSUE THREAD

**Issue by RickDoesOn** [LaG1924/AltCraft#7]
My issue list for AC that I encountered for now... Or suggestions.

----Hoppefully will be fixed next time!
----------------------------------------
list

-if there was an IP like play.forexamp.com then you will remove the port.
and if you dont want to enter a port in a different textbox
then make support to join to ips like 127.0.0.1:25565
and not like 127.0.0.1 and 25565-

-make it optimised, like i run a windows 10 PC with 8gb ram
and the server you spawn is in an island with bunch of water
then it will crashes....
and make support for teleporting to worlds and /register and /login-

-if I sometimes want to type something at MC
then at AC
it shows 1>-

-also, if there is a tall grass in the world
and the AC shows it a tnt block
then at MC the player youre looking at is like fly-hacking-

-make the client to save your nick instead of HelloOne-

-The letter § will crash the client-

-done
--------------------------
list by CarrY on Discord !! 
Make sure to fix

**Comment by LaG1924** [comment]
Everything is fixed except #11 #12 #13 #14.
