### ISSUE TITLE
Can we run AltCraft on android

### ISSUE THREAD

**Issue by codingwatching** [LaG1924/AltCraft#73]
Hi @LaG1924 can we build AltCraft to run on an android device?
We can make the control binding later

**Comment by LaG1924** [comment]
Hi @codingwatching. I do believe we can! Actually, I have it in plans for the next builds. But for now, I didn't even try to build and not added touch input controls. Even if it will compile, I do not see any sense in Android support without input support. Maybe the next stable build will have that feature...

**Comment by codingwatching** [comment]
@LaG1924 Thank you so much! This is awesome project!
