### ISSUE TITLE
When inventory and some missing entity will comeback?

### ISSUE THREAD

**Issue by ClickNinYT** [LaG1924/AltCraft#74]
Idk how to build a nether portal or go to another dimension without an inventory. Also there is some missing texture on the world.

**Comment by LaG1924** [comment]
Unfortunately, AC is not playable without side run of MC:JE. We are working on it.
Inventory will be added in next build. But when next build will be... I Don't know. Later?
Which one missing texture? BlockId is only important number for solving it. Or block type if you can see it in MC:JE.

**Comment by ClickNinYT** [comment]
What I meant about Missing Textures is there is some blocks in the world have the Unknown Block texture. Also, yeah, I think side run of MC:JE is good, but I think it will affect the performance too?

**Comment by ClickNinYT** [comment]
I could help a bit if I know C++, but I'm only know a bit of C#.

**Comment by LaG1924** [comment]
Yes, that's true. I didn't implement all of the multiple block ids. You can see a list of supported blocks in [blocks.lua](https://github.com/LaG1924/AltCraft/blob/master/cwd/assets/altcraft/scripts/blocks.lua). And, if you want to help, you can improve UI styles (HTML/CSS) or implement more block ids (Lua).

**Comment by ClickNinYT** [comment]
Okay, but what about the side-run of MC:JE? Will it affect the performance? Because thats the main difference of AC and MC:JE.

**Comment by ClickNinYT** [comment]
My Discord is: ClickNin#4252. In case you want a way to contact more faster.

**Comment by ClickNinYT** [comment]
I see.
