### ISSUE TITLE
how do you use inventory?

### ISSUE THREAD

**Issue by ClassicTube** [LaG1924/AltCraft#75]
when i press "e" nothing shows up

**Comment by LaG1924** [comment]
Inventory not yet implemented. It was in the previous build but was removed because of some major problems with it. Hope to get it back in the next stable build.

Duplicate #74

**Comment by uis246** [comment]
Try my fork

**Comment by ClassicTube** [comment]
@uis246 is it build 3 with inventory?
and if so can you make a compiled version?
