### ISSUE TITLE
Alt Craft crashes

### ISSUE THREAD

**Issue by alexsteve647** [LaG1924/AltCraft#79]
when I click on `AltCraft.exe` window opens and then crashes.
In log it says:
```
[0.00][INFO][Render][main.cpp]: Logger is configured
[0.01][ERROR][Render][Settings.cpp]: Loading settings failed: Can't open ifstream for ./settings.json: No such file or directory
[0.01][INFO][Render][Render.cpp]: Creating window: 900x480 "AltCraft"
```

**Comment by LaG1924** [comment]
Looks, like it crashed in time of graphics initialization. Have you tried the latest unstable build (from actions tab)?
Also, I need your OS, GPU driver version and GPU (and CPU but not necessary) specs.

**Comment by alexsteve647** [comment]
Yes I tried latest unstable build.

OS version: `windows 10 build 10240`
It has built-in gpu in cpu: `GMA X3500`
CPU: `Intel Core 2 Duo E7300 2.66GHz`

**Comment by alexsteve647** [comment]
So I tried the latest unstable build (from actions tab), but still window crashes.

**Comment by LaG1924** [comment]
Unfortunately, GMA X3500 is too old and does not support the required OpenGL 3 or DirectX 10. I can not do anything with it now except advise you to use a newer (2010+) discrete GPU. Add support for legacy GPU is not planned right now.

**Comment by alexsteve647** [comment]
Ok, thanks for answer!
