### ISSUE TITLE
Alt Craft is not a Windows 32 valid program

### ISSUE THREAD

**Issue by GeniusProgrammingSystem** [LaG1924/AltCraft#8]
Hello but it seems like I can't run the game on Windows Xp 32 bit can you please help me.

**Comment by LaG1924** [comment]
The current exe is compiled without the support of Windows XP, so you can not run them on this OS.
If you really need to run AltCraft on an outdated OS, you can compile it yourself.
I'm not sure about the feasibility of OS support, which is even less popular than Linux among gamers.
