### ISSUE TITLE
Build on Linux fails

### ISSUE THREAD

**Issue by lolpro11** [LaG1924/AltCraft#81]
Build Log
[log.txt](https://github.com/LaG1924/AltCraft/files/8249818/log.txt)

Let me know if you need any other details

**Comment by LaG1924** [comment]
Please check that #82 solved build error.

Build error in your log file is caused by outdated SDL2 library which does not support newest wayland 1.14. I just updated SDL2, so problem should gone.

Please, close the issue, if it's now compiles fine.

**Comment by uis246** [comment]
Try my fork if it not compiles

**Comment by lolpro11** [comment]
> Try my fork if it not compiles

Why don't you merge it in this branch?


> Please check that #82 solved build error.
> 
> Build error in your log file is caused by outdated SDL2 library which does not support newest wayland 1.14. I just updated SDL2, so problem should gone.
> 
> Please, close the issue, if it's now compiles fine.

Yes, it compiles fine. Thanks!
