### ISSUE TITLE
Render does not work in latest commit (Linux Build)

### ISSUE THREAD

**Issue by lolpro11** [LaG1924/AltCraft#83]
Hello,
Here is the log when I try to start Altcraft up.
[myeasylog.log](https://github.com/LaG1924/AltCraft/files/8338825/myeasylog.log)

Please let me know if you need anything else.

Thanks,
lolpro11

**Comment by LaG1924** [comment]
Hello. For rendering I usually need image of "does not work". Couple of errors in log is actually related to rendering, but they are appearfor some rendering settings and do not cause any problems. And your hardware information and settings (json file or screenshot) can help me solve that issue.

So, I do need info about your CPU/GPU and your Linux distro (version is important too). Your graphics settings and "render does not work" screenshot of problem is more important.

**Comment by lolpro11** [comment]
Hello, the screen is just black when I start AltCraft
![2022-03-23-232644_1600x900_scrot](https://user-images.githubusercontent.com/89674666/159855633-b131ee85-3436-4035-be4c-b89ff2c8c8ba.png)

My [settings.json](https://github.com/LaG1924/AltCraft/files/8338981/settings.txt)

My Linux Distro: Arch Linux (Rolling)
CPU: Intel i5-3437U (4) @ 2.900GHz 
GPU: Intel 3rd Gen Core processor Graphics Controller

**Comment by LaG1924** [comment]
Looks like corrupted assets: UI shader or UI markup file.

Please, check that next files exists and valid (they are not empty and doesn't contains unprintable characters):
`/assets/altcraft/scripts/ui.lua`
`/assets/altcraft/ui/main-menu.rml`
`/assets/altcraft/shaders/vert/rml.vs`
`/assets/altcraft/shaders/frag/rml.fs`

If all of it is ok, then you can just "reset" your assets. Remove /assets/ directory and fill it with assets from your revision from git (`git reset --hard HEAD` if you cloned repo) and MC assets.

**Comment by lolpro11** [comment]
Yep, the assets seem to be the issue. Thanks!
